### ISSUE TITLE
error with el.up()

### ISSUE THREAD

**Issue by vesvello** [czettnersandor/magento-quick-view-ajax#2]
Uncaught TypeError: Object #<HTMLDocument> has no method 'up'

any ideas?

**Comment by rvpatel** [comment]
This is not a issue just find 'p' tag product image on exist or not so just change on jQuery file with your tag.

**Comment by nathpaiva** [comment]
the same think, do you have some example? because I could not run anywhere!

**Comment by czettnersandor** [comment]
Sorry as now I have a full time job, I'm not planning to maintain this repository unless one of my clients needs a new feature / bugfix.

Pull requests are welcome, however.

**Comment by lplohmann** [comment]
I was having the same error. But, at least in my case, the problem was in my list.phtml I put the quick view button outside of .product-image block, making the following lines in productInfo.js expendable:

```
        $$(x_image).each(function(el, index){
            el.observe('mouseover', that.showButton);
            el.observe('mouseout', that.hideButton);
        })
```

I just commented this block out and the error went away.

If I may recommend an alteration, completely remove this piece of JS and let this visual behaviour to the CSS.

**Comment by czettnersandor** [comment]
This JS is crap, I'm even surprised I wrote this years ago. I'll rewrite this thing later. In case you want to implement it yourself, please make a pull request. ;)
